- id: auto-document
  name: Automatic API Documentation
  description: Automatically generates documentation for modified Python functions
  entry: docugen pre-commit
  language: python
  types: [python]
  require_serial: true
  args: [--max-context=16384]
